### ISSUE TITLE
Cant include config

### ISSUE THREAD

**Issue by MrUnknownGamer** [Tomelyr/Server-Hopping-Bunny#3]
Happens when started
Couldn't include file '..\sh_shb_config.lua' (File not found) (@addons/server-hopping-bunny/lua/lib/sh_shb_json.lua (line 2))

When opening serverhopping menu
[ERROR] addons/server-hopping-bunny/lua/lib/sh_shb_json.lua:29: Not found.
  1. assert - [C]:-1
   2. callbackCheck - addons/server-hopping-bunny/lua/lib/sh_shb_json.lua:29
    3. onsuccess - addons/server-hopping-bunny/lua/lib/sh_shb_json.lua:38
     4. unknown - lua/includes/modules/http.lua:34

**Comment by Tomelyr** [comment]
can replicate the bug. gonna fix it in the next few days.

**Comment by MrUnknownGamer** [comment]
Ok. Thank You

**Comment by Tomelyr** [comment]
Fixed in 874d2413651db92e5ac37c52cc366e15b59a5a23
